package ExceptionHandling;

public class FirstException {
    public static void main(String[] args) {
        //ExceptionCreator obj = new ExceptionCreator(20,21);
        //obj.fun();
        /*ExceptionInFunction exp = new ExceptionInFunction(10,20);
        try{
            ExceptionInFunction exp2 = new ExceptionInFunction(20,3);
            exp2.fun();
        }
        catch (Exception e){
            System.out.println(e.toString());
            try{
                exp.fun();
            }
            catch (Exception s){
                System.out.println(s.toString());
            }*/

        /*NestedTryCatch nt = new NestedTryCatch(20,30);
        nt.func();
        System.out.println("Object is created");
        NestedTryCatch e2 = new NestedTryCatch(20,3);
        e2.func();*/

//        ThrowException th = new ThrowException();
//        th.print();

        /*User Defined Exception Block

        * */
        /*ExcDemo ed = new ExcDemo();
        ed.funs();*/
    }
}
